"""The part of `lumen._C` that ``lumen/stream/python.rs`` defines (see
``lumen/_C.pyi``)."""

from typing import Optional, Union

from lumen._C import device

def _mps_synchronize() -> None: ...
def _cuda_synchronize(device: Optional[Union[int, str, device]] = None) -> None: ...
def _cuda_is_available() -> bool: ...
def _cuda_stream_wait(index: int, stream: int) -> None: ...
