"""The part of `lumen._C` that ``lumen/stream/python.rs`` defines (see
``lumen/_C.pyi``)."""

from typing import Optional, Sequence, Union

from lumen._C import device
from lumen.tensor._C import Tensor

def _mps_synchronize() -> None: ...
def _mps_compile(source: str) -> None: ...
def _mps_launch(
    name: str, tensors: Sequence[Tensor], args: Sequence[bytes], grid: tuple[int, int, int], groups: bool
) -> None: ...
def _mps_command_buffer() -> int: ...
def _mps_buffer(t: Tensor) -> tuple[int, int]: ...
def _cuda_synchronize(device: Optional[Union[int, str, device]] = None) -> None: ...
def _cuda_is_available() -> bool: ...
def _cuda_stream_wait(index: int, stream: int) -> None: ...
