"""The part of `lumen._C` that ``lumen/tensor/python.rs`` defines (see
``lumen/_C.pyi``)."""

from typing import Any, Optional, Sequence, Union

from lumen._C import DeviceLike

Scalar = Union[bool, int, float]

class Tensor:
    def __init__(
        self,
        data: Any,
        shape: Optional[Sequence[int]] = None,
        dtype: Optional[str] = None,
        device: Optional[DeviceLike] = None,
    ) -> None: ...
    @staticmethod
    def empty(shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None) -> Tensor:
        """Uninitialized, like ``torch.empty``: write every element before
        reading it (reading first is undefined behavior in the Rust core)."""

    @staticmethod
    def zeros(shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None) -> Tensor: ...
    @staticmethod
    def ones(shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None) -> Tensor: ...
    @staticmethod
    def full(
        shape: Sequence[int],
        value: Scalar,
        dtype: Optional[str] = None,
        device: Optional[DeviceLike] = None,
    ) -> Tensor: ...
    @staticmethod
    def arange(n: int, dtype: Optional[str] = None, device: Optional[DeviceLike] = None) -> Tensor: ...

    # metadata
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def numel(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def storage_offset(self) -> int: ...
    @property
    def storage_id(self) -> int: ...
    def is_contiguous(self) -> bool: ...
    def shares_storage_with(self, other: Tensor) -> bool: ...

    # views
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def narrow(self, dim: int, start: int, len: int) -> Tensor: ...
    def select(self, dim: int, index: int) -> Tensor: ...
    def transpose(self, a: int, b: int) -> Tensor: ...
    def permute(self, dims: Sequence[int]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: int) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def to(self, device: Optional[DeviceLike] = None, dtype: Optional[str] = None) -> Tensor:
        """This tensor converted to ``dtype`` and/or on ``device``."""
    # element access
    def get(self, index: Sequence[int]) -> Scalar: ...
    def set(self, index: Sequence[int], value: Scalar) -> None: ...
    def fill_(self, value: Scalar) -> Tensor: ...
    def zero_(self) -> Tensor: ...
    def copy_(self, src: Tensor) -> Tensor: ...
    def clone(self) -> Tensor: ...
    @property
    def _is_parameter(self) -> bool: ...
    def _placed(self, device: DeviceLike) -> Tensor: ...
    def wait_(self) -> Tensor: ...
    def item(self) -> Union[float, int, bool]: ...
    def cpu(self) -> Tensor: ...
    def tolist(self) -> Any: ...

    # DLPack / interop (attached in lumen/tensor/dlpack.py)
    def __dlpack__(
        self,
        *,
        stream: Optional[int] = -1,
        max_version: Optional[tuple[int, int]] = None,
        dl_device: Optional[tuple[int, int]] = None,
        copy: Optional[bool] = None,
    ) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def data_ptr(self) -> int: ...

    # dunder
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, tuple[int, ...]]) -> Union[Tensor, Scalar]: ...
    def __setitem__(self, key: Union[int, tuple[int, ...]], value: Scalar) -> None: ...

def _to_dlpack(t: Tensor) -> Any: ...
def _to_dlpack_versioned(t: Tensor) -> Any: ...
def _from_dlpack(capsule: Any) -> Tensor: ...
def _pack(members: Sequence[Tensor], dimension: int, device: DeviceLike) -> Optional[Tensor]: ...
