//! Attention, matched as written: `softmax(q @ k^T * scale [masked]) @ v`,
//! however traced (`F.scaled_dot_product_attention`, or written out, as
//! `run_mps_compiled.py`'s block does), run as one flash-attention kernel
//! (`ops/attention/mps.metal`, generated by `codegen.rs`) when
//! [`CompilerConfig::flash_attention`] is on: the scores and
//! probabilities never reach memory. No primitive of its own (XLA's fused
//! attention rewriters match it so too).
//!
//! What is matched, from the output back:
//!
//! ```text
//! o = dot_general(p', v')              p' = [convert] p, contracting p's last dimension
//! p = e / broadcast(reduce_sum(e))     over the last dimension (a softmax)
//! e = exp(x - broadcast(reduce_max(x)))
//! x = [select(causal, ., -inf)] [convert] [* scale] [convert] s
//! s = dot_general(q', k')              [batch..., Sq, Sk], contracting the head dimension
//! ```
//!
//! and an output transpose, if that is the only reader. The kernel computes
//! as traced: the scores as `s`'s dtype rounds them, then each cast and the
//! scale in its own dtype ([`Score`]); both dots accumulate, and the
//! softmax computes, in float32 (as the kernel does), or it is not matched.
//! The softmax is online and the probabilities are rounded to `p'`'s dtype
//! before they are normalized (flash attention's reordering). `q'`, `k'` and
//! `v'` are read where they come from, through transposes, slices,
//! broadcasts and reshapes (a grouped-query expansion of `k` and `v`, the
//! slices of a merged dot): each a strided view of a buffer, its head index
//! divided for grouped queries. The causal mask is any predicate of the
//! scores' row and column `iota`s equivalent to `j <= i + offset`.

use std::collections::HashMap;

use super::fusion::constant;
use crate::DType;
use crate::graph::{FUSION_SEPARATOR, Graph, Node, Primitive, Var};
use crate::tensor::contiguous_strides;

/// How the kernel reads (or writes) an operand: element `(batch, row, col)`
/// of the attention is at `offset + sum(batch[k] / div_k * stride_k) +
/// row * row_stride + col * col_stride` of buffer `base` (a value of the
/// graph), `batch` the batch dimensions' indices.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct Access {
    pub base: Var,
    pub offset: usize,
    /// Each batch dimension's (stride, divisor): 0 broadcasts it.
    pub batch: Vec<(usize, usize)>,
    pub row: usize,
    pub col: usize,
}

/// An attention: its node indices, and what its kernel computes.
#[derive(Debug, Clone)]
pub(crate) struct Attention {
    /// The node whose value is the attention's output.
    pub root: usize,
    /// q (row: query, col: head), k (row: key, col: head), v (row: key,
    /// col: value head) and the output (row: query, col: value head).
    pub q: Access,
    pub k: Access,
    pub v: Access,
    pub out: Access,
    /// The batch dimensions' sizes, the queries, keys, head and value head
    /// sizes.
    pub batch: Vec<usize>,
    pub sq: usize,
    pub sk: usize,
    pub h: usize,
    pub hv: usize,
    /// What each score (`q k^T` in float) goes through, in order, before
    /// the softmax.
    pub scores: Vec<Score>,
    /// A causal mask: key `j` is seen by query `i` iff `j <= i + offset`.
    pub causal: Option<i64>,
    /// The node computing each query row's log-sum-exp of its scores
    /// (`max + log(sum)`, float32, `[batch..., Sq, 1]`), if a training
    /// forward does: the kernel writes it too.
    pub lse: Option<usize>,
    /// q, k and v's dtype (the probabilities', rounded for `p @ v`), and
    /// the output's.
    pub dtype: DType,
    pub out_dtype: DType,
}

/// A step of the scores' way to the softmax, as traced.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum Score {
    /// Rounded to a dtype (the first dot's output, a cast).
    Round(DType),
    /// Multiplied by a positive constant, in a dtype.
    Mul(f64, DType),
}

/// An attention's backward, as `F.scaled_dot_product_attention`'s
/// gradient traces it (FlashAttention-2's; MLX's
/// `ScaledDotProductAttentionVJP`), on the transposed scores
/// `S^T = K Q^T` (`[batch..., Sk, Sq]`, through casts, a scale and a
/// causal mask as [`Score`]s):
///
/// ```text
/// P^T  = exp(S^T - lse)              lse: each query's log-sum-exp (the forward's)
/// dS^T = P^T (V dO^T - D) * c        D: each query's rowsum(dO * O)
/// dV = P^T dO    dK = dS^T Q    dQ = dS K
/// ```
///
/// P and dS rounded to the operands' dtype for their dots, which
/// accumulate and return float32. A fusion of it computes dV and dK (a
/// threadgroup a block of keys), or dQ (a block of queries): those of its
/// dots present.
#[derive(Debug, Clone)]
pub(crate) struct Backward {
    /// The dots computing dV, dK and dQ (`[batch..., Sk, Hv]`,
    /// `[batch..., Sk, H]`, `[batch..., Sq, H]`, float32, contiguous), each
    /// if present.
    pub dv: Option<usize>,
    pub dk: Option<usize>,
    pub dq: Option<usize>,
    /// q and dO (row: query), k and v (row: key); lse and D (one per
    /// query: its column).
    pub q: Access,
    pub k: Access,
    pub v: Access,
    pub d_o: Access,
    pub lse: Access,
    pub delta: Access,
    pub batch: Vec<usize>,
    pub sq: usize,
    pub sk: usize,
    pub h: usize,
    pub hv: usize,
    pub scores: Vec<Score>,
    pub causal: Option<i64>,
    /// What `P^T (dP^T - D)` is multiplied by: the scale.
    pub ds_scale: f64,
    /// The operands' dtype, P's and dS's for their dots.
    pub dtype: DType,
}

/// The largest head dimension the backward kernels keep rows of in
/// registers (K, V and their gradients' rows, a key block's).
pub(crate) const MAX_BACKWARD_HEAD: usize = 128;

/// The attention backward a fusion's `body` computes, if it is one.
pub(crate) fn backward_of_body(body: &Graph) -> Option<Backward> {
    let m = Matcher::new(body);
    (0..body.nodes().len()).find_map(|i| m.backward(i))
}

/// The fusion body computing `outputs` of `graph` from `bases` (its
/// inputs): every node from them back to those.
fn body_of(graph: &Graph, producer: &[Option<usize>], outputs: &[Var], bases: &[Var]) -> Graph {
    let nodes = graph.nodes();
    let mut members = Vec::new();
    let mut stack: Vec<Var> = outputs.to_vec();
    while let Some(v) = stack.pop() {
        if bases.contains(&v) {
            continue;
        }
        let n = producer[v].expect("a value the fusion computes");
        if !members.contains(&n) {
            members.push(n);
            stack.extend(&nodes[n].inputs);
        }
    }
    members.sort_unstable();
    let mut body = Graph::new();
    let mut var: HashMap<Var, Var> = HashMap::new();
    for &b in bases {
        var.insert(b, body.input(graph.type_of(b).clone()));
    }
    for &n in &members {
        let node = &nodes[n];
        let ins: Vec<Var> = node.inputs.iter().map(|v| var[v]).collect();
        let v = body.apply(node.primitive.clone(), &ins).expect("a node of the graph");
        var.insert(node.output, v);
    }
    let outputs: Vec<Var> = outputs.iter().map(|v| var[v]).collect();
    body.set_outputs(&outputs).expect("the fusion's outputs");
    body
}

/// `graph` with each attention backward (see [`Backward`]) replaced by two
/// fusions: one of dV and dK, one of dQ, their kernels named by `kernel`
/// (the nodes they replace left dead, each fusion where its last output
/// was, every reader of its outputs after it).
pub(crate) fn fuse_backward(graph: &Graph, mut kernel: impl FnMut(&Graph) -> String) -> Graph {
    let m = Matcher::new(graph);
    let nodes = graph.nodes();
    // Each fusion: where it goes, its outputs (the dots'), its inputs.
    let mut fusions: Vec<(usize, Vec<usize>, Vec<Var>)> = Vec::new();
    for i in 0..nodes.len() {
        let Some(b) = m.backward(i) else { continue };
        let (Some(dv), Some(dk), Some(dq)) = (b.dv, b.dk, b.dq) else { continue };
        let mut bases: Vec<Var> = Vec::new();
        for acc in [&b.q, &b.k, &b.v, &b.d_o, &b.lse, &b.delta] {
            if !bases.contains(&acc.base) {
                bases.push(acc.base);
            }
        }
        for outs in [vec![dv, dk], vec![dq]] {
            let at = *outs.iter().max().expect("a dot");
            let read_after = outs
                .iter()
                .all(|&o| !m.output[nodes[o].output] && m.readers[nodes[o].output].iter().all(|&r| r > at));
            if read_after {
                fusions.push((at, outs, bases.clone()));
            }
        }
    }
    if fusions.is_empty() {
        return graph.clone();
    }
    let mut out = Graph::new();
    let mut map: Vec<Var> = vec![usize::MAX; graph.types.len()];
    for &v in graph.inputs() {
        map[v] = out.input(graph.type_of(v).clone());
    }
    for (i, node) in nodes.iter().enumerate() {
        // An output of a fusion placed after it: mapped there.
        if fusions.iter().any(|(at, outs, _)| outs.contains(&i) && i > *at) {
            continue;
        }
        let Some((_, outs, bases)) = fusions.iter().find(|(at, _, _)| *at == i) else {
            let inputs: Vec<Var> = node.inputs.iter().map(|&v| map[v]).collect();
            map[node.output] = out.apply(node.primitive.clone(), &inputs).expect("a node of the graph");
            continue;
        };
        let outputs: Vec<Var> = outs.iter().map(|&o| nodes[o].output).collect();
        let body = body_of(graph, &m.producer, &outputs, bases);
        let name = kernel(&body);
        let label = match outs.len() {
            2 => "flash_attention_backward(dk, dv)",
            _ => "flash_attention_backward(dq)",
        };
        let fusion = Primitive::Fusion {
            name,
            label,
            body,
        };
        let reads: Vec<Var> = bases.iter().map(|&b| map[b]).collect();
        let first = out.apply(fusion, &reads).expect("a fusion typed as its first output");
        map[outputs[0]] = first;
        for (index, &o) in outputs.iter().enumerate().skip(1) {
            let ty = graph.type_of(o).clone();
            map[o] = out
                .apply(Primitive::FusionOutput { index, ty }, &[first])
                .expect("the fusion's output");
        }
    }
    let outputs: Vec<Var> = graph.outputs().iter().map(|&v| map[v]).collect();
    out.set_outputs(&outputs).expect("values of the graph");
    out
}

/// Whether `acc`'s `rows` by `cols` elements of a batch index are
/// addressed in 32 bits (as the kernels do, within a batch index).
fn fits32(acc: &Access, rows: usize, cols: usize) -> bool {
    (acc.row * (rows - 1) + acc.col * (cols - 1)) < (1 << 32)
}

/// The largest head dimension the kernels keep a row of in registers.
pub(crate) const MAX_HEAD: usize = 256;

/// The attentions in `graph`, none overlapping.
pub(crate) fn attentions(graph: &Graph) -> Vec<Attention> {
    let m = Matcher::new(graph);
    let mut found: Vec<Attention> = Vec::new();
    for (i, node) in graph.nodes().iter().enumerate() {
        let dot = m.live[i] && matches!(node.primitive, Primitive::DotGeneral { .. });
        if let Some(a) = dot.then(|| m.attention(i)).flatten() {
            found.push(a);
        }
    }
    found
}

/// The attention a fusion's `body` computes, if it is one: its output the
/// attention's, or its epilogue's (the elementwise primitives and reshapes
/// after it, applied as it writes each output).
pub(crate) fn of_body(body: &Graph) -> Option<Attention> {
    attentions(body).into_iter().next()
}

/// `graph` with each attention replaced by a fusion of its nodes (inputs:
/// the buffers it reads), its kernel named by `kernel`; the nodes it
/// replaces are left dead. With `epilogues`, the fusion takes the
/// elementwise primitives and reshapes after the attention too, each the
/// only reader of the one before (a residual add, a cast): its output's
/// flat index is the attention's; their other operands (not runtime
/// `scalars`) are read there, through broadcasts, reshapes, casts and
/// constants (which the fusion computes), from buffers it takes as inputs.
pub(crate) fn fuse(
    graph: &Graph,
    epilogues: bool,
    scalars: &[Var],
    mut kernel: impl FnMut(&Graph) -> String,
) -> Graph {
    let m = Matcher::new(graph);
    // Each attention, its epilogue's nodes (in order), its last node, and
    // the buffers its epilogue reads.
    let found: Vec<(Attention, Vec<usize>, usize, Vec<Var>)> = attentions(graph)
        .into_iter()
        .map(|a| {
            let (mut chain, mut leaves) = match epilogues {
                true => m.epilogue(a.root, scalars),
                false => (Vec::new(), Vec::new()),
            };
            // Its log-sum-exp, an output of its fusion, is read after it:
            // without an epilogue if one would end past a reader of it.
            let lse_read = |end: usize| {
                a.lse.is_none_or(|n| m.readers[graph.nodes()[n].output].iter().all(|&r| r > end))
            };
            if !lse_read(chain.last().copied().unwrap_or(a.root)) {
                (chain, leaves) = (Vec::new(), Vec::new());
            }
            let end = chain.last().copied().unwrap_or(a.root);
            (a, chain, end, leaves)
        })
        .filter(|(a, _, end, _)| {
            a.lse
                .is_none_or(|n| m.readers[graph.nodes()[n].output].iter().all(|r| r > end))
        })
        .collect();
    if found.is_empty() {
        return graph.clone();
    }
    let nodes = graph.nodes();
    let mut out = Graph::new();
    let mut map: Vec<Var> = vec![usize::MAX; graph.types.len()];
    for &v in graph.inputs() {
        map[v] = out.input(graph.type_of(v).clone());
    }
    for (i, node) in nodes.iter().enumerate() {
        // A log-sum-exp after its attention: the fusion's output already.
        if found.iter().any(|(a, _, end, _)| a.lse == Some(i) && i > *end) {
            continue;
        }
        let inputs: Vec<Var> = node.inputs.iter().map(|&v| map[v]).collect();
        let Some((a, chain, _, leaves)) = found.iter().find(|(_, _, end, _)| *end == i) else {
            map[node.output] = out
                .apply(node.primitive.clone(), &inputs)
                .expect("a node of the graph");
            continue;
        };
        // The fusion's inputs: the buffers it reads; its body, every node
        // from its output back to them.
        let mut bases: Vec<Var> = Vec::new();
        for &b in [a.q.base, a.k.base, a.v.base].iter().chain(leaves) {
            if !bases.contains(&b) {
                bases.push(b);
            }
        }
        let lse = a.lse.map(|n| nodes[n].output);
        let outputs: Vec<Var> = std::iter::once(node.output).chain(lse).collect();
        let body = body_of(graph, &m.producer, &outputs, &bases);
        let name = kernel(&body);
        // Profiled as the attention, then its epilogue's primitives:
        // `flash_attention → reshape → add`.
        let label = std::iter::once("flash_attention")
            .chain(chain.iter().map(|&n| graph.label(&nodes[n])));
        let label = crate::graph::intern(label.collect::<Vec<_>>().join(FUSION_SEPARATOR));
        let fusion = Primitive::Fusion { name, label, body };
        let reads: Vec<Var> = bases.iter().map(|&b| map[b]).collect();
        map[node.output] = out
            .apply(fusion, &reads)
            .expect("a fusion typed as the attention");
        if let Some(v) = lse {
            let ty = graph.type_of(v).clone();
            let lse = Primitive::FusionOutput { index: 1, ty };
            map[v] = out.apply(lse, &[map[node.output]]).expect("the fusion's output");
        }
    }
    let outputs: Vec<Var> = graph.outputs().iter().map(|&v| map[v]).collect();
    out.set_outputs(&outputs).expect("values of the graph");
    out
}

struct Matcher<'a> {
    graph: &'a Graph,
    producer: Vec<Option<usize>>,
    /// Each value's live readers (once each), and whether it is an output.
    readers: Vec<Vec<usize>>,
    output: Vec<bool>,
    live: Vec<bool>,
}

impl<'a> Matcher<'a> {
    /// The epilogue after node `root`: its nodes in order (none: `root`
    /// alone), and the values its other operands read (the fusion's
    /// inputs), as [`fuse`] takes it.
    fn epilogue(&self, root: usize, scalars: &[Var]) -> (Vec<usize>, Vec<Var>) {
        use Primitive::*;
        let nodes = self.graph.nodes();
        let (mut end, mut chain, mut leaves) = (root, Vec::new(), Vec::new());
        loop {
            let v = nodes[end].output;
            let [u] = self.readers[v][..] else { break };
            let n = &nodes[u];
            let step =
                super::fusion::elementwise(&n.primitive) || matches!(n.primitive, Reshape { .. });
            if self.output[v] || !step {
                break;
            }
            let mut found = Vec::new();
            let others = n.inputs.iter().filter(|&&x| x != v);
            if !others
                .into_iter()
                .all(|&x| self.leaves(x, scalars, &mut found))
            {
                break;
            }
            for leaf in found {
                if !leaves.contains(&leaf) {
                    leaves.push(leaf);
                }
            }
            end = u;
            chain.push(u);
        }
        (chain, leaves)
    }

    /// Whether operand `v` of an epilogue can be read at its output's
    /// index, adding the buffers it reads to `leaves`: a value (not a
    /// runtime scalar), or broadcasts, reshapes, casts and constants of
    /// such.
    fn leaves(&self, v: Var, scalars: &[Var], leaves: &mut Vec<Var>) -> bool {
        use Primitive::*;
        let Some(n) = self.node(v) else {
            leaves.push(v);
            return !scalars.contains(&v);
        };
        match n.primitive {
            Full { .. } | Iota { .. } => true,
            BroadcastInDim { .. } | Reshape { .. } | Cast { .. } => {
                self.leaves(n.inputs[0], scalars, leaves)
            }
            _ => {
                leaves.push(v);
                true
            }
        }
    }

    fn new(graph: &'a Graph) -> Self {
        let nodes = graph.nodes();
        let n = graph.types.len();
        let mut producer = vec![None; n];
        for (i, node) in nodes.iter().enumerate() {
            producer[node.output] = Some(i);
        }
        let mut output = vec![false; n];
        graph.outputs().iter().for_each(|&v| output[v] = true);
        let mut live = vec![false; nodes.len()];
        let mut live_var = output.clone();
        for (i, node) in nodes.iter().enumerate().rev() {
            if live_var[node.output] {
                live[i] = true;
                node.inputs.iter().for_each(|&v| live_var[v] = true);
            }
        }
        let mut readers: Vec<Vec<usize>> = vec![Vec::new(); n];
        for (i, node) in nodes.iter().enumerate().filter(|&(i, _)| live[i]) {
            for &v in &node.inputs {
                if readers[v].last() != Some(&i) {
                    readers[v].push(i);
                }
            }
        }
        Matcher {
            graph,
            producer,
            readers,
            output,
            live,
        }
    }

    fn node(&self, v: Var) -> Option<&'a Node> {
        self.producer[v].map(|i| &self.graph.nodes()[i])
    }

    /// Whether `v` is read by one node alone (and is no output).
    fn single(&self, v: Var) -> bool {
        !self.output[v] && self.readers[v].len() == 1
    }

    /// `v` through a cast read only once, if it is one.
    fn uncast(&self, v: Var) -> Var {
        match self.node(v) {
            Some(n)
                if matches!(n.primitive, Primitive::Cast { .. })
                    && self.single(v) =>
            {
                n.inputs[0]
            }
            _ => v,
        }
    }

    /// The value a broadcast (perhaps of a keepdim reshape) of `v` comes
    /// from, through values read once (or `shared`, read by the
    /// log-sum-exp too).
    fn unbroadcast(&self, mut v: Var, shared: Option<Var>) -> Var {
        while let Some(n) = self.node(v) {
            match n.primitive {
                Primitive::BroadcastInDim { .. } | Primitive::Reshape { .. }
                    if self.single(v) || shared == Some(v) =>
                {
                    v = n.inputs[0]
                }
                _ => break,
            }
        }
        v
    }

    /// The value of the scalar constant `v` (a `full`, perhaps broadcast or
    /// cast).
    fn scalar(&self, v: Var) -> Option<f64> {
        if !constant(self.graph, &self.producer, v) {
            return None;
        }
        let mut v = v;
        loop {
            let n = self.node(v)?;
            match &n.primitive {
                Primitive::Full { fill_value, .. } => return Some(fill_value.to_f64()),
                Primitive::BroadcastInDim { .. }
                | Primitive::Reshape { .. }
                | Primitive::Cast { .. } => v = n.inputs[0],
                _ => return None,
            }
        }
    }

    /// The attention backward whose `P^T` node `i` recomputes, if it is
    /// one (see [`Backward`]).
    fn backward(&self, i: usize) -> Option<Backward> {
        use Primitive::*;
        let nodes = self.graph.nodes();
        let ty = |v: Var| self.graph.type_of(v);
        let dot = |n: usize| match &nodes[n].primitive {
            DotGeneral {
                lhs_contracting,
                rhs_contracting,
                lhs_batch,
                rhs_batch,
                accum_dtype,
                output_dtype,
            } => Some((lhs_contracting, rhs_contracting, lhs_batch, rhs_batch, *accum_dtype, *output_dtype)),
            _ => None,
        };
        let f32 = DType::F32;
        // P^T = exp(S^T - lse).
        if !matches!(nodes[i].primitive, Exp) || !self.live[i] {
            return None;
        }
        let pt = nodes[i].output;
        let sub = self
            .node(nodes[i].inputs[0])
            .filter(|n| matches!(n.primitive, Sub) && self.single(nodes[i].inputs[0]))?;
        let (x, lse_b) = (sub.inputs[0], sub.inputs[1]);
        let nb = ty(x).shape.len().checked_sub(2)?;
        let (s, scores, causal) = self.scores(x, nb, true)?;
        let (lc1, rc1, lb1, rb1, acc1, _) = dot(s)?;
        let (k_, q_) = (nodes[s].inputs[0], nodes[s].inputs[1]);
        if lb1.len() != nb || lc1.len() != 1 || rc1.len() != 1 || acc1 != f32 || ty(x).dtype != f32 {
            return None;
        }
        let free = |rank: usize, used: &[&[usize]]| (0..rank).find(|d| used.iter().all(|u| !u.contains(d)));
        let (kf, qf) = (
            free(ty(k_).shape.len(), &[lb1, lc1])?,
            free(ty(q_).shape.len(), &[rb1, rc1])?,
        );
        let dtype = ty(q_).dtype;
        // Its readers: dS^T's product, and dV's dot (perhaps through a cast).
        let (mut m1, mut dv) = (None, None);
        for &r in &self.readers[pt] {
            match &nodes[r].primitive {
                Mul if m1.is_none() => m1 = Some(r),
                Cast { .. } if dv.is_none() => {
                    let c = nodes[r].output;
                    let [d] = self.readers[c][..] else { return None };
                    (self.single(c) && nodes[d].inputs[0] == c).then_some(())?;
                    dv = Some(d);
                }
                DotGeneral { .. } if dv.is_none() && nodes[r].inputs[0] == pt => dv = Some(r),
                _ => return None,
            }
        }
        if self.output[pt] {
            return None;
        }
        // dS^T = (P^T (dP^T - D)) * c, perhaps cast; dP^T = V dO^T.
        let m1 = &nodes[m1?];
        let other = *m1.inputs.iter().find(|&&v| v != pt)?;
        let sub2 = self
            .node(other)
            .filter(|n| matches!(n.primitive, Sub) && self.single(other))?;
        let (dpt, d_b) = (sub2.inputs[0], sub2.inputs[1]);
        let dpt_node = self.producer[dpt].filter(|_| self.single(dpt))?;
        let (lc2, rc2, lb2, rb2, acc2, out2) = dot(dpt_node)?;
        let (v_, do_) = (nodes[dpt_node].inputs[0], nodes[dpt_node].inputs[1]);
        if lb2.len() != nb || lc2.len() != 1 || rc2.len() != 1 || acc2 != f32 || out2 != f32 {
            return None;
        }
        let (vf, dof) = (
            free(ty(v_).shape.len(), &[lb2, lc2])?,
            free(ty(do_).shape.len(), &[rb2, rc2])?,
        );
        let m1_out = m1.output;
        let [m2] = self.readers[m1_out][..] else { return None };
        if self.output[m1_out] || !matches!(nodes[m2].primitive, Mul) {
            return None;
        }
        let (a, b) = (nodes[m2].inputs[0], nodes[m2].inputs[1]);
        let ds_scale = match a == m1_out {
            true => self.scalar(b)?,
            false => self.scalar(a)?,
        };
        let mut ds = nodes[m2].output;
        if let [c] = self.readers[ds][..]
            && !self.output[ds]
            && matches!(nodes[c].primitive, Cast { .. })
        {
            ds = nodes[c].output;
        }
        // dS^T's readers: dK's dot (contracting the queries, with q) and
        // dQ's (contracting the keys, with k).
        let (mut dk, mut dq) = (None, None);
        for &r in &self.readers[ds] {
            let (lc, rc, lb, _, acc, out) = dot(r)?;
            if nodes[r].inputs[0] != ds || *lb != (0..nb).collect::<Vec<_>>() || acc != f32 || out != f32 {
                return None;
            }
            match (lc.as_slice(), rc.as_slice()) {
                ([c], [d]) if *c == nb + 1 && nodes[r].inputs[1] == q_ && *d == qf && dk.is_none() => dk = Some(r),
                ([c], [d]) if *c == nb && nodes[r].inputs[1] == k_ && *d == kf && dq.is_none() => dq = Some(r),
                _ => return None,
            }
        }
        if self.output[ds] || (dk.is_none() && dq.is_none()) {
            return None;
        }
        // dV's dot: P^T dO, contracting the queries.
        if let Some(d) = dv {
            let (lc, rc, lb, _, acc, out) = dot(d)?;
            // dO's queries (free in dP^T) contracted.
            let ok = *lb == (0..nb).collect::<Vec<_>>()
                && *lc == [nb + 1]
                && nodes[d].inputs[1] == do_
                && *rc == [dof]
                && acc == f32
                && out == f32;
            ok.then_some(())?;
        }
        // P and dS rounded to the operands' dtype; the operands one dtype.
        let same = [k_, q_, v_, do_].iter().all(|&t| ty(t).dtype == dtype)
            && ty(ds).dtype == dtype
            && dv.is_none_or(|d| ty(nodes[d].inputs[0]).dtype == dtype);
        let shape = &ty(x).shape;
        let (sk, sq) = (shape[nb], shape[nb + 1]);
        let (h, hv) = (ty(q_).shape[rc1[0]], ty(v_).shape[lc2[0]]);
        let fits = |n: usize| n.is_multiple_of(8) && n > 0 && n <= MAX_BACKWARD_HEAD;
        let float = matches!(dtype, DType::F16 | DType::BF16 | DType::F32);
        if !same || !float || !fits(h) || !fits(hv) || sq == 0 || sk == 0 {
            return None;
        }
        let all: Vec<usize> = (0..nb).collect();
        let q = self.access(q_, rb1, qf, rc1[0])?;
        let k = self.access(k_, lb1, kf, lc1[0])?;
        let v = self.access(v_, lb2, vf, lc2[0])?;
        let d_o = self.access(do_, rb2, dof, rc2[0])?;
        let lse = self.access(lse_b, &all, nb, nb + 1)?;
        let delta = self.access(d_b, &all, nb, nb + 1)?;
        // lse and D: one per query (the same for each key), float32.
        let per_query = |acc: &Access, v: Var| acc.row == 0 && ty(v).dtype == f32;
        if !per_query(&lse, lse_b) || !per_query(&delta, d_b) {
            return None;
        }
        if !fits32(&q, sq, h) || !fits32(&k, sk, h) || !fits32(&v, sk, hv) || !fits32(&d_o, sq, hv) {
            return None;
        }
        Some(Backward {
            dv,
            dk,
            dq,
            q,
            k,
            v,
            d_o,
            lse,
            delta,
            batch: shape[..nb].to_vec(),
            sq,
            sk,
            h,
            hv,
            scores,
            causal,
            ds_scale,
            dtype,
        })
    }

    /// The scores `x` back to their dot (its node): the casts, the scale
    /// and the causal mask each goes through, as [`Score`]s in order (from
    /// the dot's rounding), and the mask's offset. `transposed`: `x`'s rows
    /// are the keys, its columns the queries (a backward's `S^T`).
    fn scores(&self, x: Var, nb: usize, transposed: bool) -> Option<(usize, Vec<Score>, Option<i64>)> {
        use Primitive::*;
        let ty = |v: Var| self.graph.type_of(v);
        let (mut v, mut scale, mut causal) = (x, None, None);
        let mut scores = Vec::new();
        let s = loop {
            let n = self.node(v)?;
            if v != x && !self.single(v) {
                return None;
            }
            let dtype = ty(n.output).dtype;
            match &n.primitive {
                DotGeneral { .. } => break self.producer[v]?,
                Cast { .. } => {
                    scores.push(Score::Round(dtype));
                    v = n.inputs[0];
                }
                Mul if scale.is_none() => {
                    let (a, b) = (n.inputs[0], n.inputs[1]);
                    let (c, rest) = match self.scalar(b) {
                        Some(c) => (c, a),
                        None => (self.scalar(a)?, b),
                    };
                    scale = Some(c);
                    scores.push(Score::Mul(c, dtype));
                    v = rest;
                }
                Select if causal.is_none() => {
                    if self.scalar(n.inputs[2]) != Some(f64::NEG_INFINITY) {
                        return None;
                    }
                    causal = Some(self.causal(n.inputs[0], nb, transposed)?);
                    v = n.inputs[1];
                }
                _ => return None,
            }
        };
        // A positive scale keeps the mask's -inf where it is.
        if scale.is_some_and(|c| !(c > 0.0 && c.is_finite())) {
            return None;
        }
        scores.push(Score::Round(ty(self.graph.nodes()[s].output).dtype));
        scores.reverse();
        Some((s, scores, causal))
    }

    /// The log-sum-exp `m + log(l)` of a softmax's keepdim max `m` and sum
    /// `l` (each read by the softmax and it alone), in float32: its node.
    fn lse(&self, m: Var, l: Var) -> Option<usize> {
        let nodes = self.graph.nodes();
        let two = |v: Var| self.readers[v].len() == 2 && !self.output[v];
        if !two(m) || !two(l) {
            return None;
        }
        let add = *self.readers[m]
            .iter()
            .find(|&&r| matches!(nodes[r].primitive, Primitive::Add))?;
        let log = *nodes[add].inputs.iter().find(|&&v| v != m)?;
        let is_log = self.node(log).is_some_and(|n| {
            matches!(n.primitive, Primitive::Log) && n.inputs[0] == l && self.single(log)
        });
        let f32 = self.graph.type_of(nodes[add].output).dtype == DType::F32;
        (is_log && f32 && nodes[add].inputs.contains(&m)).then_some(add)
    }

    /// `v`, the reduction `is` over the last dimension of `x` (read only
    /// by it), if it is one: `x`.
    fn reduced(&self, v: Var, is: fn(&Primitive) -> bool) -> Option<Var> {
        let n = self.node(v)?;
        let x = *n.inputs.first()?;
        let last = self.graph.type_of(x).shape.len().checked_sub(1)?;
        let axes = match &n.primitive {
            Primitive::ReduceSum { axes, .. } | Primitive::ReduceMax { axes } => axes,
            _ => return None,
        };
        (is(&n.primitive) && axes.as_slice() == [last] && self.single(v)).then_some(x)
    }

    /// The attention whose second dot is node `i`.
    fn attention(&self, i: usize) -> Option<Attention> {
        use Primitive::*;
        let nodes = self.graph.nodes();
        let ty = |v: Var| self.graph.type_of(v);
        let DotGeneral {
            lhs_contracting: lc2,
            rhs_contracting: rc2,
            lhs_batch: lb2,
            rhs_batch: rb2,
            ..
        } = &nodes[i].primitive
        else {
            return None;
        };
        let (p_, v_) = (nodes[i].inputs[0], nodes[i].inputs[1]);
        let nb = lb2.len();
        let (pr, vr) = (ty(p_).shape.len(), ty(v_).shape.len());
        if pr != nb + 2 || vr != nb + 2 || *lb2 != (0..nb).collect::<Vec<_>>() || *lc2 != [nb + 1] {
            return None;
        }
        // The softmax: p = e / broadcast(sum(e)), e = exp(x - broadcast(max(x))).
        if !self.single(p_) {
            return None;
        }
        let p = self.uncast(p_);
        let div = self
            .node(p)
            .filter(|n| matches!(n.primitive, Div) && self.single(p))?;
        let e = div.inputs[0];
        let exp = self.node(e).filter(|n| matches!(n.primitive, Exp))?;
        if self.readers[e].len() != 2 || self.output[e] {
            return None;
        }
        let sub = self
            .node(exp.inputs[0])
            .filter(|n| matches!(n.primitive, Sub) && self.single(exp.inputs[0]))?;
        let x = sub.inputs[0];
        // A training forward's log-sum-exp, max + log(sum): it reads the
        // keepdim max and sum too.
        let (l, m) = (
            self.unbroadcast(div.inputs[1], None),
            self.unbroadcast(sub.inputs[1], None),
        );
        let lse = self.lse(m, l);
        let shared = |v: Var| lse.is_some().then_some(v);
        let sum = self.unbroadcast(l, shared(l));
        let max = self.unbroadcast(m, shared(m));
        if self.reduced(sum, |p| matches!(p, ReduceSum { .. }))? != e {
            return None;
        }
        if self.reduced(max, |p| matches!(p, ReduceMax { .. }))? != x
            || self.readers[x].len() != 2
            || self.output[x]
        {
            return None;
        }
        let (s, scores, causal) = self.scores(x, nb, false)?;
        let s = &nodes[s];
        // The kernel accumulates the dots, and computes the softmax, in
        // float32.
        let f32 = |p: &Primitive| match p {
            DotGeneral { accum_dtype, .. } | ReduceSum { accum_dtype, .. } => *accum_dtype == DType::F32,
            _ => false,
        };
        let (dot1, dot2, sum) = (&s.primitive, &nodes[i].primitive, &self.node(sum)?.primitive);
        if ty(x).dtype != DType::F32 || !f32(dot1) || !f32(dot2) || !f32(sum) {
            return None;
        }
        let DotGeneral {
            lhs_contracting: lc1,
            rhs_contracting: rc1,
            lhs_batch: lb1,
            rhs_batch: rb1,
            ..
        } = &s.primitive
        else {
            unreachable!("a dot")
        };
        let (q_, k_) = (s.inputs[0], s.inputs[1]);
        let (qr, kr) = (ty(q_).shape.len(), ty(k_).shape.len());
        if lb1.len() != nb || lc1.len() != 1 || rc1.len() != 1 || qr != nb + 2 || kr != nb + 2 {
            return None;
        }
        // Each operand's free dimension: the query's, the key's, the value
        // head's.
        let free = |rank: usize, used: &[&[usize]]| {
            (0..rank).find(|d| used.iter().all(|u| !u.contains(d)))
        };
        let (qf, kf, vf) = (
            free(qr, &[lb1, lc1])?,
            free(kr, &[rb1, rc1])?,
            free(vr, &[rb2, rc2])?,
        );
        let sty = ty(s.output);
        let (sq, sk) = (sty.shape[nb], sty.shape[nb + 1]);
        let (h, hv) = (ty(q_).shape[lc1[0]], ty(v_).shape[vf]);
        let batch: Vec<usize> = sty.shape[..nb].to_vec();
        let dtype = ty(q_).dtype;
        let float = matches!(dtype, DType::F16 | DType::BF16 | DType::F32);
        let fits = |n: usize| n.is_multiple_of(8) && n > 0 && n <= MAX_HEAD;
        if !float || ty(k_).dtype != dtype || ty(v_).dtype != dtype || ty(p_).dtype != dtype {
            return None;
        }
        if !fits(h) || !fits(hv) || sq == 0 || sk == 0 || ty(v_).shape[rc2[0]] != sk {
            return None;
        }
        // The operands, as views of the buffers they read.
        let q = self.access(q_, lb1, qf, lc1[0])?;
        let k = self.access(k_, rb1, kf, rc1[0])?;
        let v = self.access(v_, rb2, rc2[0], vf)?;
        if !fits32(&q, sq, h) || !fits32(&k, sk, h) || !fits32(&v, sk, hv) {
            return None;
        }
        // The output, [batch..., Sq, Hv], or its transpose (the only reader).
        let o = nodes[i].output;
        let (root, perm) = match self.readers[o].as_slice() {
            [r] if !self.output[o] => match &nodes[*r].primitive {
                Transpose { permutation } => (*r, permutation.clone()),
                _ => (i, (0..nb + 2).collect()),
            },
            _ => (i, (0..nb + 2).collect()),
        };
        let strides = contiguous_strides(&ty(nodes[root].output).shape);
        let stride = |d: usize| strides[perm.iter().position(|&p| p == d).expect("a permutation")];
        let out = Access {
            base: nodes[root].output,
            offset: 0,
            batch: (0..nb).map(|d| (stride(d), 1)).collect(),
            row: stride(nb),
            col: stride(nb + 1),
        };
        Some(Attention {
            root,
            q,
            k,
            v,
            out,
            batch,
            sq,
            sk,
            h,
            hv,
            scores,
            causal,
            lse,
            dtype,
            out_dtype: ty(nodes[root].output).dtype,
        })
    }

    /// `v` as an operand of a kernel: read from the buffer it comes from
    /// (as [`Self::view`]), at batch dimensions `b`, its rows along `row`
    /// and columns along `col` (neither divided).
    fn access(&self, v: Var, b: &[usize], row: usize, col: usize) -> Option<Access> {
        let (base, offset, dims) = self.view(v);
        let one = |d: usize| (dims[d].1 == 1).then_some(dims[d].0);
        Some(Access {
            base,
            offset,
            batch: b.iter().map(|&d| dims[d]).collect(),
            row: one(row)?,
            col: one(col)?,
        })
    }

    /// The causal offset of predicate `v` (of the scores' shape, its row
    /// dimension `nb`, its column `nb + 1`; `transposed`, the keys' rows):
    /// key `j` is seen by query `i` iff `j <= i + offset`.
    fn causal(&self, v: Var, nb: usize, transposed: bool) -> Option<i64> {
        use Primitive::*;
        // `a < b`, or `a <= b` (`select(a < b, a < b, a == b)`): a - b, and
        // whether equal is in.
        let n = self.node(v)?;
        let (a, b, inclusive) = match n.primitive {
            Lt => (n.inputs[0], n.inputs[1], false),
            Select => {
                let less = self
                    .node(n.inputs[0])
                    .filter(|l| matches!(l.primitive, Lt))?;
                let eq = self
                    .node(n.inputs[2])
                    .filter(|e| matches!(e.primitive, Eq))?;
                if n.inputs[1] != n.inputs[0] || less.inputs != eq.inputs {
                    return None;
                }
                (less.inputs[0], less.inputs[1], true)
            }
            _ => return None,
        };
        let (ai, aj, ac) = self.affine(a, nb)?;
        let (bi, bj, bc) = self.affine(b, nb)?;
        // (ci) i + (cj) j + c0 < 0 (or <= 0) with cj = 1, ci = -1: j < i - c0.
        let (ci, cj, c0) = (ai - bi, aj - bj, ac - bc);
        // Transposed, the query is the column, the key the row.
        let (ci, cj) = if transposed { (cj, ci) } else { (ci, cj) };
        if (ci, cj) != (-1, 1) {
            return None;
        }
        Some(if inclusive { -c0 } else { -c0 - 1 })
    }

    /// `v` as `ci * i + cj * j + c0`, `i` and `j` the scores' row and
    /// column indices (an `iota` along dimension `nb`, `nb + 1`).
    fn affine(&self, v: Var, nb: usize) -> Option<(i64, i64, i64)> {
        use Primitive::*;
        let n = self.node(v)?;
        match &n.primitive {
            Iota { dimension, .. } if *dimension == nb => Some((1, 0, 0)),
            Iota { dimension, .. } if *dimension == nb + 1 => Some((0, 1, 0)),
            Full {
                fill_value, shape, ..
            } if shape.is_empty() => {
                let c = fill_value.to_f64();
                (c.fract() == 0.0).then_some((0, 0, c as i64))
            }
            BroadcastInDim { .. } | Reshape { .. } | Cast { .. } => {
                let (ci, cj, c) = self.affine(n.inputs[0], nb)?;
                // Only constants are broadcast: an index would move.
                (matches!(n.primitive, Cast { .. }) || (ci, cj) == (0, 0))
                    .then_some((ci, cj, c))
            }
            Add | Sub => {
                let (a, b) = (self.affine(n.inputs[0], nb)?, self.affine(n.inputs[1], nb)?);
                let s = if matches!(n.primitive, Add) { 1 } else { -1 };
                Some((a.0 + s * b.0, a.1 + s * b.1, a.2 + s * b.2))
            }
            _ => None,
        }
    }

    /// `v` as read from the buffer it comes from: back through transposes,
    /// slices, broadcasts and reshapes read only once: that buffer, the
    /// offset, and each of `v`'s dimensions' (stride, divisor).
    fn view(&self, v: Var) -> (Var, usize, Vec<(usize, usize)>) {
        use Primitive::*;
        let own = || {
            let shape = &self.graph.type_of(v).shape;
            (
                v,
                0,
                contiguous_strides(shape)
                    .into_iter()
                    .map(|s| (s, 1))
                    .collect(),
            )
        };
        let Some(n) = self.node(v).filter(|_| self.single(v)) else {
            return own();
        };
        let layout = matches!(
            n.primitive,
            Transpose { .. } | Slice { .. } | BroadcastInDim { .. } | Reshape { .. }
        );
        if !layout {
            return own();
        }
        let x = n.inputs[0];
        let (base, mut offset, dims) = self.view(x);
        let xs = &self.graph.type_of(x).shape;
        let shape = &self.graph.type_of(v).shape;
        let dims = match &n.primitive {
            Transpose { permutation } => permutation.iter().map(|&p| dims[p]).collect(),
            Slice { start_indices, .. } => {
                for (d, &s) in start_indices.iter().enumerate() {
                    if s != 0 && dims[d].1 != 1 {
                        return own();
                    }
                    offset += s * dims[d].0;
                }
                dims
            }
            BroadcastInDim {
                broadcast_dimensions,
                ..
            } => {
                let mut out = vec![(0, 1); shape.len()];
                for (k, &d) in broadcast_dimensions.iter().enumerate() {
                    if xs[k] == shape[d] {
                        out[d] = dims[k];
                    }
                }
                out
            }
            Reshape { .. } => match reshaped(xs, &dims, shape) {
                Some(out) => out,
                None => return own(),
            },
            _ => unreachable!("a layout primitive"),
        };
        (base, offset, dims)
    }
}

/// The (stride, divisor) of each dimension of `shape`, a reshape of
/// `from` read at `dims`: its non-1 dimensions grouped with `from`'s by
/// product, each group one to one, a split of one, or a merge of
/// contiguous dimensions or of one and broadcast ones (its index divided).
fn reshaped(
    from: &[usize],
    dims: &[(usize, usize)],
    shape: &[usize],
) -> Option<Vec<(usize, usize)>> {
    let ins: Vec<(usize, (usize, usize))> = from
        .iter()
        .zip(dims)
        .filter(|(n, _)| **n != 1)
        .map(|(&n, &d)| (n, d))
        .collect();
    let outs: Vec<usize> = (0..shape.len()).filter(|&d| shape[d] != 1).collect();
    let mut out = vec![(0, 1); shape.len()];
    let (mut a, mut b) = (0, 0);
    while a < ins.len() || b < outs.len() {
        let (mut pa, mut pb) = (ins.get(a)?.0, shape[*outs.get(b)?]);
        let (a0, b0) = (a, b);
        while pa != pb {
            if pa < pb {
                a += 1;
                pa *= ins.get(a)?.0;
            } else {
                b += 1;
                pb *= shape[*outs.get(b)?];
            }
        }
        let group = &ins[a0..=a];
        let targets = &outs[b0..=b];
        match (group, targets) {
            ([(_, d)], [t]) => out[*t] = *d,
            ([(_, (s, 1))], ts) => {
                // A split: each part's stride, the inner ones' product.
                let mut stride = *s;
                for &t in ts.iter().rev() {
                    out[t] = (stride, 1);
                    stride *= shape[t];
                }
            }
            (gs, [t]) => {
                let (_, (s0, d0)) = gs[0];
                let rest = &gs[1..];
                if rest.iter().all(|(_, (s, d))| *s == 0 && *d == 1) {
                    // One dimension and broadcast ones: its index divided.
                    let inner: usize = rest.iter().map(|(n, _)| n).product();
                    out[*t] = (s0, d0 * inner);
                } else if gs
                    .windows(2)
                    .all(|w| w[0].1.1 == 1 && w[1].1.1 == 1 && w[0].1.0 == w[1].1.0 * w[1].0)
                {
                    out[*t] = (gs.last()?.1.0, 1);
                } else {
                    return None;
                }
            }
            _ => return None,
        }
        a += 1;
        b += 1;
    }
    Some(out)
}
