//! Attention, matched as written: `softmax(q @ k^T * scale [masked]) @ v`,
//! however traced (`F.scaled_dot_product_attention`, or written out, as
//! `run_mps_compiled.py`'s block does), run as one flash-attention kernel
//! (`attention.metal`, generated by `codegen.rs`) when
//! [`CompilerConfig::flash_attention`] is on: the scores and
//! probabilities never reach memory. No primitive of its own (XLA's fused
//! attention rewriters match it so too).
//!
//! What is matched, from the output back:
//!
//! ```text
//! o = dot_general(p', v')              p' = [convert] p, contracting p's last dimension
//! p = e / broadcast(reduce_sum(e))     over the last dimension (a softmax)
//! e = exp(x - broadcast(reduce_max(x)))
//! x = [select(causal, ., -inf)] [convert] [* scale] [convert] s
//! s = dot_general(q', k')              [batch..., Sq, Sk], contracting the head dimension
//! ```
//!
//! and an output transpose, if that is the only reader. `q'`, `k'` and
//! `v'` are read where they come from, through transposes, slices,
//! broadcasts and reshapes (a grouped-query expansion of `k` and `v`, the
//! slices of a merged dot): each a strided view of a buffer, its head index
//! divided for grouped queries. The causal mask is any predicate of the
//! scores' row and column `iota`s equivalent to `j <= i + offset`.

use std::collections::HashMap;

use super::fusion::constant;
use crate::DType;
use crate::graph::{Graph, Node, Primitive, Var};
use crate::tensor::contiguous_strides;

/// How the kernel reads (or writes) an operand: element `(batch, row, col)`
/// of the attention is at `offset + sum(batch[k] / div_k * stride_k) +
/// row * row_stride + col * col_stride` of buffer `base` (a value of the
/// graph), `batch` the batch dimensions' indices.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct Access {
    pub base: Var,
    pub offset: usize,
    /// Each batch dimension's (stride, divisor): 0 broadcasts it.
    pub batch: Vec<(usize, usize)>,
    pub row: usize,
    pub col: usize,
}

/// An attention: its node indices, and what its kernel computes.
#[derive(Debug, Clone)]
pub(crate) struct Attention {
    /// The node whose value is the attention's output.
    pub root: usize,
    /// q (row: query, col: head), k (row: key, col: head), v (row: key,
    /// col: value head) and the output (row: query, col: value head).
    pub q: Access,
    pub k: Access,
    pub v: Access,
    pub out: Access,
    /// The batch dimensions' sizes, the queries, keys, head and value head
    /// sizes.
    pub batch: Vec<usize>,
    pub sq: usize,
    pub sk: usize,
    pub h: usize,
    pub hv: usize,
    /// What the scores are multiplied by (positive).
    pub scale: f64,
    /// A causal mask: key `j` is seen by query `i` iff `j <= i + offset`.
    pub causal: Option<i64>,
    /// q, k and v's dtype (the probabilities', rounded for `p @ v`), and
    /// the output's.
    pub dtype: DType,
    pub out_dtype: DType,
}

/// The largest head dimension the kernels keep a row of in registers.
pub(crate) const MAX_HEAD: usize = 256;

/// The attentions in `graph`, none overlapping.
pub(crate) fn attentions(graph: &Graph) -> Vec<Attention> {
    let m = Matcher::new(graph);
    let mut found: Vec<Attention> = Vec::new();
    for (i, node) in graph.nodes().iter().enumerate() {
        let dot = m.live[i] && matches!(node.primitive, Primitive::DotGeneral { .. });
        if let Some(a) = dot.then(|| m.attention(i)).flatten() {
            found.push(a);
        }
    }
    found
}

/// The attention a fusion's `body` computes, if it is one (its output an
/// attention's, of the body's inputs).
pub(crate) fn of_body(body: &Graph) -> Option<Attention> {
    let out = body.outputs()[0];
    attentions(body)
        .into_iter()
        .find(|a| body.nodes()[a.root].output == out)
}

/// `graph` with each attention replaced by a fusion of its nodes (inputs:
/// the buffers it reads), its kernel named by `kernel`; the nodes it
/// replaces are left dead.
pub(crate) fn fuse(graph: &Graph, mut kernel: impl FnMut(&Graph) -> String) -> Graph {
    let found = attentions(graph);
    if found.is_empty() {
        return graph.clone();
    }
    let nodes = graph.nodes();
    let mut producer = vec![None; graph.types.len()];
    for (i, n) in nodes.iter().enumerate() {
        producer[n.output] = Some(i);
    }
    let mut out = Graph::new();
    let mut map: Vec<Var> = vec![usize::MAX; graph.types.len()];
    for &v in graph.inputs() {
        map[v] = out.input(graph.type_of(v).clone());
    }
    for (i, node) in nodes.iter().enumerate() {
        let inputs: Vec<Var> = node.inputs.iter().map(|&v| map[v]).collect();
        let Some(a) = found.iter().find(|a| a.root == i) else {
            map[node.output] = out
                .apply(node.primitive.clone(), &inputs)
                .expect("a node of the graph");
            continue;
        };
        // The fusion's body: every node from the output back to the
        // buffers it reads (its inputs).
        let mut bases: Vec<Var> = Vec::new();
        for b in [a.q.base, a.k.base, a.v.base] {
            if !bases.contains(&b) {
                bases.push(b);
            }
        }
        let mut members = Vec::new();
        let mut stack = vec![i];
        while let Some(n) = stack.pop() {
            if members.contains(&n) {
                continue;
            }
            members.push(n);
            for &v in &nodes[n].inputs {
                if !bases.contains(&v) {
                    stack.push(producer[v].expect("a value the attention computes"));
                }
            }
        }
        members.sort_unstable();
        let mut body = Graph::new();
        let mut var: HashMap<Var, Var> = HashMap::new();
        for &b in &bases {
            var.insert(b, body.input(graph.type_of(b).clone()));
        }
        for &n in &members {
            let node = &nodes[n];
            let ins: Vec<Var> = node.inputs.iter().map(|v| var[v]).collect();
            let v = body
                .apply(node.primitive.clone(), &ins)
                .expect("a node of the graph");
            var.insert(node.output, v);
        }
        body.set_outputs(&[var[&node.output]])
            .expect("the attention's output");
        let name = kernel(&body);
        let fusion = Primitive::Fusion {
            name,
            label: "flash_attention",
            body,
        };
        let reads: Vec<Var> = bases.iter().map(|&b| map[b]).collect();
        map[node.output] = out
            .apply(fusion, &reads)
            .expect("a fusion typed as the attention");
    }
    let outputs: Vec<Var> = graph.outputs().iter().map(|&v| map[v]).collect();
    out.set_outputs(&outputs).expect("values of the graph");
    out
}

struct Matcher<'a> {
    graph: &'a Graph,
    producer: Vec<Option<usize>>,
    /// Each value's live readers (once each), and whether it is an output.
    readers: Vec<Vec<usize>>,
    output: Vec<bool>,
    live: Vec<bool>,
}

impl<'a> Matcher<'a> {
    fn new(graph: &'a Graph) -> Self {
        let nodes = graph.nodes();
        let n = graph.types.len();
        let mut producer = vec![None; n];
        for (i, node) in nodes.iter().enumerate() {
            producer[node.output] = Some(i);
        }
        let mut output = vec![false; n];
        graph.outputs().iter().for_each(|&v| output[v] = true);
        let mut live = vec![false; nodes.len()];
        let mut live_var = output.clone();
        for (i, node) in nodes.iter().enumerate().rev() {
            if live_var[node.output] {
                live[i] = true;
                node.inputs.iter().for_each(|&v| live_var[v] = true);
            }
        }
        let mut readers: Vec<Vec<usize>> = vec![Vec::new(); n];
        for (i, node) in nodes.iter().enumerate().filter(|&(i, _)| live[i]) {
            for &v in &node.inputs {
                if readers[v].last() != Some(&i) {
                    readers[v].push(i);
                }
            }
        }
        Matcher {
            graph,
            producer,
            readers,
            output,
            live,
        }
    }

    fn node(&self, v: Var) -> Option<&'a Node> {
        self.producer[v].map(|i| &self.graph.nodes()[i])
    }

    /// Whether `v` is read by one node alone (and is no output).
    fn single(&self, v: Var) -> bool {
        !self.output[v] && self.readers[v].len() == 1
    }

    /// `v` through a cast read only once, if it is one.
    fn uncast(&self, v: Var) -> Var {
        match self.node(v) {
            Some(n)
                if matches!(n.primitive, Primitive::ConvertElementType { .. })
                    && self.single(v) =>
            {
                n.inputs[0]
            }
            _ => v,
        }
    }

    /// The value a broadcast (perhaps of a keepdim reshape) of `v` comes
    /// from.
    fn unbroadcast(&self, mut v: Var) -> Var {
        while let Some(n) = self.node(v) {
            match n.primitive {
                Primitive::BroadcastInDim { .. } | Primitive::Reshape { .. } if self.single(v) => {
                    v = n.inputs[0]
                }
                _ => break,
            }
        }
        v
    }

    /// The value of the scalar constant `v` (a `full`, perhaps broadcast or
    /// cast).
    fn scalar(&self, v: Var) -> Option<f64> {
        if !constant(self.graph, &self.producer, v) {
            return None;
        }
        let mut v = v;
        loop {
            let n = self.node(v)?;
            match &n.primitive {
                Primitive::Full { fill_value, .. } => return Some(fill_value.to_f64()),
                Primitive::BroadcastInDim { .. }
                | Primitive::Reshape { .. }
                | Primitive::ConvertElementType { .. } => v = n.inputs[0],
                _ => return None,
            }
        }
    }

    /// `v`, the reduction `is` over the last dimension of `x` (read only
    /// by it), if it is one: `x`.
    fn reduced(&self, v: Var, is: fn(&Primitive) -> bool) -> Option<Var> {
        let n = self.node(v)?;
        let x = *n.inputs.first()?;
        let last = self.graph.type_of(x).shape.len().checked_sub(1)?;
        let axes = match &n.primitive {
            Primitive::ReduceSum { axes, .. } | Primitive::ReduceMax { axes } => axes,
            _ => return None,
        };
        (is(&n.primitive) && axes.as_slice() == [last] && self.single(v)).then_some(x)
    }

    /// The attention whose second dot is node `i`.
    fn attention(&self, i: usize) -> Option<Attention> {
        use Primitive::*;
        let nodes = self.graph.nodes();
        let ty = |v: Var| self.graph.type_of(v);
        let DotGeneral {
            lhs_contracting: lc2,
            rhs_contracting: rc2,
            lhs_batch: lb2,
            rhs_batch: rb2,
            ..
        } = &nodes[i].primitive
        else {
            return None;
        };
        let (p_, v_) = (nodes[i].inputs[0], nodes[i].inputs[1]);
        let nb = lb2.len();
        let (pr, vr) = (ty(p_).shape.len(), ty(v_).shape.len());
        if pr != nb + 2 || vr != nb + 2 || *lb2 != (0..nb).collect::<Vec<_>>() || *lc2 != [nb + 1] {
            return None;
        }
        // The softmax: p = e / broadcast(sum(e)), e = exp(x - broadcast(max(x))).
        if !self.single(p_) {
            return None;
        }
        let p = self.uncast(p_);
        let div = self
            .node(p)
            .filter(|n| matches!(n.primitive, Div) && self.single(p))?;
        let e = div.inputs[0];
        let sum = self.unbroadcast(div.inputs[1]);
        if self.reduced(sum, |p| matches!(p, ReduceSum { .. }))? != e {
            return None;
        }
        let exp = self.node(e).filter(|n| matches!(n.primitive, Exp))?;
        if self.readers[e].len() != 2 || self.output[e] {
            return None;
        }
        let sub = self
            .node(exp.inputs[0])
            .filter(|n| matches!(n.primitive, Sub) && self.single(exp.inputs[0]))?;
        let x = sub.inputs[0];
        let max = self.unbroadcast(sub.inputs[1]);
        if self.reduced(max, |p| matches!(p, ReduceMax { .. }))? != x
            || self.readers[x].len() != 2
            || self.output[x]
        {
            return None;
        }
        // Back to the scores: casts, a scale, a causal mask.
        let (mut v, mut scale, mut causal) = (x, 1.0, None);
        let s = loop {
            let n = self.node(v)?;
            if v != x && !self.single(v) {
                return None;
            }
            match &n.primitive {
                DotGeneral { .. } => break n,
                ConvertElementType { .. } => v = n.inputs[0],
                Mul if scale == 1.0 => {
                    let (a, b) = (n.inputs[0], n.inputs[1]);
                    let (c, rest) = match self.scalar(b) {
                        Some(c) => (c, a),
                        None => (self.scalar(a)?, b),
                    };
                    (scale, v) = (c, rest);
                }
                Div if scale == 1.0 => {
                    scale = 1.0 / self.scalar(n.inputs[1])?;
                    v = n.inputs[0];
                }
                Select if causal.is_none() => {
                    if self.scalar(n.inputs[2]) != Some(f64::NEG_INFINITY) {
                        return None;
                    }
                    causal = Some(self.causal(n.inputs[0], nb)?);
                    v = n.inputs[1];
                }
                _ => return None,
            }
        };
        if !(scale > 0.0 && scale.is_finite()) {
            return None;
        }
        let DotGeneral {
            lhs_contracting: lc1,
            rhs_contracting: rc1,
            lhs_batch: lb1,
            rhs_batch: rb1,
            ..
        } = &s.primitive
        else {
            unreachable!("a dot")
        };
        let (q_, k_) = (s.inputs[0], s.inputs[1]);
        let (qr, kr) = (ty(q_).shape.len(), ty(k_).shape.len());
        if lb1.len() != nb || lc1.len() != 1 || rc1.len() != 1 || qr != nb + 2 || kr != nb + 2 {
            return None;
        }
        // Each operand's free dimension: the query's, the key's, the value
        // head's.
        let free = |rank: usize, used: &[&[usize]]| {
            (0..rank).find(|d| used.iter().all(|u| !u.contains(d)))
        };
        let (qf, kf, vf) = (
            free(qr, &[lb1, lc1])?,
            free(kr, &[rb1, rc1])?,
            free(vr, &[rb2, rc2])?,
        );
        let sty = ty(s.output);
        let (sq, sk) = (sty.shape[nb], sty.shape[nb + 1]);
        let (h, hv) = (ty(q_).shape[lc1[0]], ty(v_).shape[vf]);
        let batch: Vec<usize> = sty.shape[..nb].to_vec();
        let dtype = ty(q_).dtype;
        let float = matches!(dtype, DType::F16 | DType::BF16 | DType::F32);
        let fits = |n: usize| n.is_multiple_of(8) && n > 0 && n <= MAX_HEAD;
        if !float || ty(k_).dtype != dtype || ty(v_).dtype != dtype || ty(p_).dtype != dtype {
            return None;
        }
        if !fits(h) || !fits(hv) || sq == 0 || sk == 0 || ty(v_).shape[rc2[0]] != sk {
            return None;
        }
        // The operands, as views of the buffers they read.
        let access = |v: Var, b: &[usize], row: usize, col: usize| -> Option<Access> {
            let (base, offset, dims) = self.view(v);
            let one = |d: usize| (dims[d].1 == 1).then_some(dims[d].0);
            Some(Access {
                base,
                offset,
                batch: b.iter().map(|&d| dims[d]).collect(),
                row: one(row)?,
                col: one(col)?,
            })
        };
        let q = access(q_, lb1, qf, lc1[0])?;
        let k = access(k_, rb1, kf, rc1[0])?;
        let v = access(v_, rb2, rc2[0], vf)?;
        // Within a batch index the kernels address in 32 bits.
        let fits32 = |acc: &Access, rows: usize, cols: usize| {
            (acc.row * (rows - 1) + acc.col * (cols - 1)) < (1 << 32)
        };
        if !fits32(&q, sq, h) || !fits32(&k, sk, h) || !fits32(&v, sk, hv) {
            return None;
        }
        // The output, [batch..., Sq, Hv], or its transpose (the only reader).
        let o = nodes[i].output;
        let (root, perm) = match self.readers[o].as_slice() {
            [r] if !self.output[o] => match &nodes[*r].primitive {
                Transpose { permutation } => (*r, permutation.clone()),
                _ => (i, (0..nb + 2).collect()),
            },
            _ => (i, (0..nb + 2).collect()),
        };
        let strides = contiguous_strides(&ty(nodes[root].output).shape);
        let stride = |d: usize| strides[perm.iter().position(|&p| p == d).expect("a permutation")];
        let out = Access {
            base: nodes[root].output,
            offset: 0,
            batch: (0..nb).map(|d| (stride(d), 1)).collect(),
            row: stride(nb),
            col: stride(nb + 1),
        };
        Some(Attention {
            root,
            q,
            k,
            v,
            out,
            batch,
            sq,
            sk,
            h,
            hv,
            scale,
            causal,
            dtype,
            out_dtype: ty(nodes[root].output).dtype,
        })
    }

    /// The causal offset of predicate `v` (of the scores' shape, its row
    /// dimension `nb`, its column `nb + 1`): key `j` is seen by query `i`
    /// iff `j <= i + offset`.
    fn causal(&self, v: Var, nb: usize) -> Option<i64> {
        use Primitive::*;
        // `a < b`, or `a <= b` (`select(a < b, a < b, a == b)`): a - b, and
        // whether equal is in.
        let n = self.node(v)?;
        let (a, b, inclusive) = match n.primitive {
            Lt => (n.inputs[0], n.inputs[1], false),
            Select => {
                let less = self
                    .node(n.inputs[0])
                    .filter(|l| matches!(l.primitive, Lt))?;
                let eq = self
                    .node(n.inputs[2])
                    .filter(|e| matches!(e.primitive, Eq))?;
                if n.inputs[1] != n.inputs[0] || less.inputs != eq.inputs {
                    return None;
                }
                (less.inputs[0], less.inputs[1], true)
            }
            _ => return None,
        };
        let (ai, aj, ac) = self.affine(a, nb)?;
        let (bi, bj, bc) = self.affine(b, nb)?;
        // (ci) i + (cj) j + c0 < 0 (or <= 0) with cj = 1, ci = -1: j < i - c0.
        let (ci, cj, c0) = (ai - bi, aj - bj, ac - bc);
        if (ci, cj) != (-1, 1) {
            return None;
        }
        Some(if inclusive { -c0 } else { -c0 - 1 })
    }

    /// `v` as `ci * i + cj * j + c0`, `i` and `j` the scores' row and
    /// column indices (an `iota` along dimension `nb`, `nb + 1`).
    fn affine(&self, v: Var, nb: usize) -> Option<(i64, i64, i64)> {
        use Primitive::*;
        let n = self.node(v)?;
        match &n.primitive {
            Iota { dimension, .. } if *dimension == nb => Some((1, 0, 0)),
            Iota { dimension, .. } if *dimension == nb + 1 => Some((0, 1, 0)),
            Full {
                fill_value, shape, ..
            } if shape.is_empty() => {
                let c = fill_value.to_f64();
                (c.fract() == 0.0).then_some((0, 0, c as i64))
            }
            BroadcastInDim { .. } | Reshape { .. } | ConvertElementType { .. } => {
                let (ci, cj, c) = self.affine(n.inputs[0], nb)?;
                // Only constants are broadcast: an index would move.
                (matches!(n.primitive, ConvertElementType { .. }) || (ci, cj) == (0, 0))
                    .then_some((ci, cj, c))
            }
            Add | Sub => {
                let (a, b) = (self.affine(n.inputs[0], nb)?, self.affine(n.inputs[1], nb)?);
                let s = if matches!(n.primitive, Add) { 1 } else { -1 };
                Some((a.0 + s * b.0, a.1 + s * b.1, a.2 + s * b.2))
            }
            _ => None,
        }
    }

    /// `v` as read from the buffer it comes from: back through transposes,
    /// slices, broadcasts and reshapes read only once: that buffer, the
    /// offset, and each of `v`'s dimensions' (stride, divisor).
    fn view(&self, v: Var) -> (Var, usize, Vec<(usize, usize)>) {
        use Primitive::*;
        let own = || {
            let shape = &self.graph.type_of(v).shape;
            (
                v,
                0,
                contiguous_strides(shape)
                    .into_iter()
                    .map(|s| (s, 1))
                    .collect(),
            )
        };
        let Some(n) = self.node(v).filter(|_| self.single(v)) else {
            return own();
        };
        let layout = matches!(
            n.primitive,
            Transpose { .. } | Slice { .. } | BroadcastInDim { .. } | Reshape { .. }
        );
        if !layout {
            return own();
        }
        let x = n.inputs[0];
        let (base, mut offset, dims) = self.view(x);
        let xs = &self.graph.type_of(x).shape;
        let shape = &self.graph.type_of(v).shape;
        let dims = match &n.primitive {
            Transpose { permutation } => permutation.iter().map(|&p| dims[p]).collect(),
            Slice { start_indices, .. } => {
                for (d, &s) in start_indices.iter().enumerate() {
                    if s != 0 && dims[d].1 != 1 {
                        return own();
                    }
                    offset += s * dims[d].0;
                }
                dims
            }
            BroadcastInDim {
                broadcast_dimensions,
                ..
            } => {
                let mut out = vec![(0, 1); shape.len()];
                for (k, &d) in broadcast_dimensions.iter().enumerate() {
                    if xs[k] == shape[d] {
                        out[d] = dims[k];
                    }
                }
                out
            }
            Reshape { .. } => match reshaped(xs, &dims, shape) {
                Some(out) => out,
                None => return own(),
            },
            _ => unreachable!("a layout primitive"),
        };
        (base, offset, dims)
    }
}

/// The (stride, divisor) of each dimension of `shape`, a reshape of
/// `from` read at `dims`: its non-1 dimensions grouped with `from`'s by
/// product, each group one to one, a split of one, or a merge of
/// contiguous dimensions or of one and broadcast ones (its index divided).
fn reshaped(
    from: &[usize],
    dims: &[(usize, usize)],
    shape: &[usize],
) -> Option<Vec<(usize, usize)>> {
    let ins: Vec<(usize, (usize, usize))> = from
        .iter()
        .zip(dims)
        .filter(|(n, _)| **n != 1)
        .map(|(&n, &d)| (n, d))
        .collect();
    let outs: Vec<usize> = (0..shape.len()).filter(|&d| shape[d] != 1).collect();
    let mut out = vec![(0, 1); shape.len()];
    let (mut a, mut b) = (0, 0);
    while a < ins.len() || b < outs.len() {
        let (mut pa, mut pb) = (ins.get(a)?.0, shape[*outs.get(b)?]);
        let (a0, b0) = (a, b);
        while pa != pb {
            if pa < pb {
                a += 1;
                pa *= ins.get(a)?.0;
            } else {
                b += 1;
                pb *= shape[*outs.get(b)?];
            }
        }
        let group = &ins[a0..=a];
        let targets = &outs[b0..=b];
        match (group, targets) {
            ([(_, d)], [t]) => out[*t] = *d,
            ([(_, (s, 1))], ts) => {
                // A split: each part's stride, the inner ones' product.
                let mut stride = *s;
                for &t in ts.iter().rev() {
                    out[t] = (stride, 1);
                    stride *= shape[t];
                }
            }
            (gs, [t]) => {
                let (_, (s0, d0)) = gs[0];
                let rest = &gs[1..];
                if rest.iter().all(|(_, (s, d))| *s == 0 && *d == 1) {
                    // One dimension and broadcast ones: its index divided.
                    let inner: usize = rest.iter().map(|(n, _)| n).product();
                    out[*t] = (s0, d0 * inner);
                } else if gs
                    .windows(2)
                    .all(|w| w[0].1.1 == 1 && w[1].1.1 == 1 && w[0].1.0 == w[1].1.0 * w[1].0)
                {
                    out[*t] = (gs.last()?.1.0, 1);
                } else {
                    return None;
                }
            }
            _ => return None,
        }
        a += 1;
        b += 1;
    }
    Some(out)
}
