"""The part of `lumen._C` that ``lumen/graph/python.rs`` defines (see
``lumen/_C.pyi``)."""

from typing import Any, Optional, Sequence

from lumen._C import DeviceLike
from lumen.tensor._C import Tensor

class Graph:
    """A graph of primitive ops, built by tracing (``lumen/graph/``)."""

    def __init__(self) -> None: ...
    def input(self, dtype: str, shape: Sequence[int]) -> int: ...
    def apply(self, name: str, inputs: Sequence[int], params: Optional[dict[str, Any]] = None) -> int: ...
    def type_of(self, var: int) -> tuple[str, list[int]]: ...
    def inputs(self) -> list[int]: ...
    def outputs(self) -> list[int]: ...
    def nodes(self) -> list[dict[str, Any]]:
        """Each node: ``primitive``, ``text`` (with its parameters),
        ``fusion`` (``kernel``, ``body``, Metal ``source``; or None),
        ``inputs`` and ``output`` values."""
    def set_outputs(self, outputs: Sequence[int]) -> None: ...
    def run(self, inputs: Sequence[Tensor]) -> list[Tensor]: ...

class Plan:
    """A graph compiled for execution by ``device``'s graph compiler (on
    MPS, with its elementwise ops fused), with its memory planned."""

    def __init__(self, graph: Graph, device: Optional[DeviceLike] = None) -> None: ...
    @property
    def workspace_bytes(self) -> int: ...
    def steps(self) -> list[dict[str, Any]]:
        """Each step, as ``Graph.nodes``, with ``inputs`` and ``output`` as
        ``(buffer, dtype, shape)``."""
    def run(self, inputs: Sequence[Tensor]) -> list[Tensor]: ...
