"""The part of `lumen._C` that ``lumen/ops/python.rs`` defines (see
``lumen/_C.pyi``)."""

from typing import Any

from lumen._C import DeviceLike
from lumen.tensor._C import Scalar, Tensor

def _register_kernel(name: str, device: DeviceLike, kernel: Any) -> None: ...
def _unregister_kernel(name: str, device: DeviceLike) -> bool: ...
def _registered_ops() -> list[tuple[str, str]]: ...
def _dummy_op(t: Tensor, value: Scalar) -> None: ...
