"""Type stub for the native `lumen._C` extension module."""

from typing import Any, Literal, Optional, Sequence, Union

__version__: str

Scalar = Union[bool, int, float]

class Tensor:
    def __init__(
        self,
        data: Any,
        shape: Optional[Sequence[int]] = None,
        dtype: Optional[str] = None,
    ) -> None: ...
    @staticmethod
    def zeros(shape: Sequence[int], dtype: Optional[str] = None) -> Tensor: ...
    @staticmethod
    def full(shape: Sequence[int], value: Scalar, dtype: Optional[str] = None) -> Tensor: ...
    @staticmethod
    def arange(n: int, dtype: Optional[str] = None) -> Tensor: ...

    # metadata
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def numel(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def storage_offset(self) -> int: ...
    @property
    def storage_id(self) -> int: ...
    def is_contiguous(self) -> bool: ...
    def shares_storage_with(self, other: Tensor) -> bool: ...

    # views
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def narrow(self, dim: int, start: int, len: int) -> Tensor: ...
    def select(self, dim: int, index: int) -> Tensor: ...
    def transpose(self, a: int, b: int) -> Tensor: ...
    def permute(self, dims: Sequence[int]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: int) -> Tensor: ...
    def contiguous(self) -> Tensor: ...

    # element access
    def get(self, index: Sequence[int]) -> Scalar: ...
    def set(self, index: Sequence[int], value: Scalar) -> None: ...
    def tolist(self) -> Any: ...

    # dunder
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, tuple[int, ...]]) -> Union[Tensor, Scalar]: ...
    def __setitem__(self, key: Union[int, tuple[int, ...]], value: Scalar) -> None: ...

class device:
    """A device type plus an optional index, modeled on ``torch.device``."""

    def __init__(self, device: Union[str, "device"], index: Optional[int] = None) -> None: ...
    @property
    def type(self) -> Literal["cpu", "mps", "cuda"]: ...
    @property
    def index(self) -> Optional[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Config:
    """Process-wide runtime settings; use the ``lumen.config`` instance."""

    memory_caching: bool

config: Config
