"""Type stub for the native `lumen._C` extension module."""

from typing import Any, Literal, Optional, Sequence, Union

__version__: str

Scalar = Union[bool, int, float]

DeviceLike = Union[str, "device"]

class Tensor:
    def __init__(
        self,
        data: Any,
        shape: Optional[Sequence[int]] = None,
        dtype: Optional[str] = None,
        device: Optional[DeviceLike] = None,
    ) -> None: ...
    @staticmethod
    def empty(
        shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None
    ) -> Tensor:
        """Uninitialized, like ``torch.empty``: write every element before
        reading it (reading first is undefined behavior in the Rust core)."""
    @staticmethod
    def zeros(
        shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None
    ) -> Tensor: ...
    @staticmethod
    def ones(
        shape: Sequence[int], dtype: Optional[str] = None, device: Optional[DeviceLike] = None
    ) -> Tensor: ...
    @staticmethod
    def full(
        shape: Sequence[int],
        value: Scalar,
        dtype: Optional[str] = None,
        device: Optional[DeviceLike] = None,
    ) -> Tensor: ...
    @staticmethod
    def arange(
        n: int, dtype: Optional[str] = None, device: Optional[DeviceLike] = None
    ) -> Tensor: ...

    # metadata
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def numel(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def storage_offset(self) -> int: ...
    @property
    def storage_id(self) -> int: ...
    def is_contiguous(self) -> bool: ...
    def shares_storage_with(self, other: Tensor) -> bool: ...

    # views
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def narrow(self, dim: int, start: int, len: int) -> Tensor: ...
    def select(self, dim: int, index: int) -> Tensor: ...
    def transpose(self, a: int, b: int) -> Tensor: ...
    def permute(self, dims: Sequence[int]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: int) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def to(self, device: DeviceLike) -> Tensor: ...

    # element access
    def get(self, index: Sequence[int]) -> Scalar: ...
    def set(self, index: Sequence[int], value: Scalar) -> None: ...
    def fill_(self, value: Scalar) -> Tensor: ...
    def zero_(self) -> Tensor: ...
    def tolist(self) -> Any: ...

    # DLPack / interop
    def __dlpack__(self, stream: Optional[Any] = None) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def data_ptr(self) -> int: ...

    # dunder
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, tuple[int, ...]]) -> Union[Tensor, Scalar]: ...
    def __setitem__(self, key: Union[int, tuple[int, ...]], value: Scalar) -> None: ...

class device:
    """A device type plus an optional index, modeled on ``torch.device``."""

    def __init__(self, device: Union[str, "device"], index: Optional[int] = None) -> None: ...
    @property
    def type(self) -> Literal["cpu", "mps", "cuda"]: ...
    @property
    def index(self) -> Optional[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Config:
    """Process-wide runtime settings; use the ``lumen.config`` instance."""

    memory_caching: bool

config: Config

def _register_kernel(name: str, device: DeviceLike, kernel: Any) -> None: ...
def _unregister_kernel(name: str, device: DeviceLike) -> bool: ...
def _registered_ops() -> list[tuple[str, str]]: ...
def _from_dlpack(capsule: Any) -> Tensor: ...
def _mps_synchronize() -> None: ...
def _cuda_synchronize(device: Optional[Union[int, str, device]] = None) -> None: ...
