"""The part of `lumen._C` that ``lumen/safetensors/python.rs`` defines (see
``lumen/_C.pyi``); ``lumen.safetensors`` wraps it."""

import os
from typing import Any, Optional, Sequence, Union

from lumen._C import DeviceLike
from lumen.tensor._C import Tensor

class safe_open:
    """An open safetensors file, read a tensor at a time (``lumen.safetensors``)."""

    def __init__(self, filename: Union[str, "os.PathLike[str]"], device: Optional[DeviceLike] = None) -> None: ...
    def keys(self) -> list[str]: ...
    def offset_keys(self) -> list[str]: ...
    def metadata(self) -> Optional[dict[str, str]]: ...
    def get_tensor(self, name: str) -> Tensor: ...
    def get_tensors(self) -> list[tuple[str, Tensor]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "safe_open": ...
    def __exit__(self, *args: Any) -> None: ...

def _safetensors_serialize(tensors: Sequence[tuple[str, Tensor]], metadata: Optional[dict[str, str]] = None) -> bytes: ...
def _safetensors_save_file(tensors: Sequence[tuple[str, Tensor]], path: str, metadata: Optional[dict[str, str]] = None) -> None: ...
def _safetensors_deserialize(data: bytes, device: Optional[DeviceLike] = None) -> list[tuple[str, Tensor]]: ...
