"""The part of `lumen._C` that ``lumen/profiler/python.rs`` defines (see
``lumen/_C.pyi``); ``lumen.profiler`` wraps it."""

from typing import Any, Optional, Sequence

def _profiler_start(activities: Sequence[str], profile_memory: bool, record_shapes: bool) -> None: ...
def _profiler_stop() -> _Profile: ...
def _profiler_enabled() -> bool: ...
def _profiler_cuda_timing() -> bool: ...
def _record_function_enter(name: str) -> _RecordFunction: ...

class _RecordFunction:
    """An open ``record_function`` range; ``exit`` closes it."""

    def exit(self) -> None: ...

class _Profile:
    """A finished session's events."""

    def events(self) -> list[dict[str, Any]]: ...
    def key_averages(self) -> list[dict[str, Any]]: ...
    def table(self, sort_by: Optional[str] = None, row_limit: Optional[int] = None) -> str: ...
    def chrome_trace(self) -> str: ...
